-- 코드를 입력하세요
SELECT PRODUCT_CODE, (P.PRICE * O.TOTAL_AMOUNT) SALES
FROM PRODUCT P JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) TOTAL_AMOUNT
                    FROM OFFLINE_SALE
                    GROUP BY PRODUCT_ID) O
            ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE;